version: '3.8'

services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - SKIP_PREFLIGHT_CHECK=true
      - NEXT_PUBLIC_APP_NAME="EbmScitech Web App"
      - NEXT_PUBLIC_URL_DEV="http://145.223.19.73:3000"
      - NEXT_PUBLIC_API_URL_DEV="https://inbiota.duckdns.org"
      - NEXT_PUBLIC_API_URL_PROD="https://inbiota.duckdns.org"
    restart: always