services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=base64:rx3mTNB3LFAMtmv8JYwviFWJer8JcVABm9cU8MjI3KM=
      - SESSION_SECURE_COOKIE=false
      - APP_URL=https://inbiota.duckdns.org
      - SESSION_DOMAIN=145.223.19.73
      - SESSION_SAME_SITE=Lax
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=inbiota
      - DB_USERNAME=root
      - DB_PASSWORD=ebm@Inbiota1
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
    networks:
      - laravel-network
    ports:
      - 8000:8000
    command: sh -c "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ebm@Inbiota1
      MYSQL_DATABASE: inbiota
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - laravel-network
    ports:
      - 3307:3306

  composer:
    image: composer:2.6.2
    container_name: composer
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  db-data:
