<?php

namespace Tests;

use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Support\Facades\DB;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        DB::delete("DELETE FROM bioaktivitas");
        DB::delete("DELETE FROM emailsub");
        DB::delete("DELETE FROM questionsub");
        DB::delete("DELETE FROM sbt");
        DB::delete("DELETE FROM senyawa");
        DB::delete("DELETE FROM tanaman");
        DB::delete("DELETE FROM users");
    }
}
